### ISSUE TITLE
Docker Container läuft, Zugriff aber nicht möglich

### ISSUE THREAD

**Issue by KopfKrieg** [equitania/myodoo-docker#2]
Hallo, kleines Problem: Wir haben einen Server auf welchem bereits diverse Docker Container laufen, bekommen aber eine Myodoo-Instanz nicht zum Laufen.

Wir würden gerne Version 10 verwenden, der Beschreibung nach müssten folgende zwei Befehle ja reichen:

> docker run -d --restart=always -v pg-myodoo10:/var/lib/postgresql/data/ -e POSTGRES_USER=myodoo -e POSTGRES_PASSWORD=myodoo --name "myodoo-10-db" postgres:9.6.9
> docker run -d --restart=always -p 10069:8069 --name="myodoo-10-public" -v myodoo10:/opt/odoo/data --link myodoo-10-db:db myodoo/myodoo-10-public:180527 start

Die Container starten auch, aber unter Port 10069 ist kein Zugriff möglich. Der Port ist laut netstat/ss auch nicht geöffnet (exposed). Getestet wurde das jetzt in diversen Konfigurationen unter Ubuntu 16.04, Ubuntu 18.04 sowie eine aktuellen Archlinux.

Wissen Sie evtl. eine Lösung? Optimalerweise würden wir gerne ein compose-file verwenden, aber auch das ist fehlgeschlagen:

```
version: '2'

services:
  myodoo:
    image: myodoo/myodoo-10-public:180527
    restart: always
    ports:
      - "10069:8069"
    depends_on:
      - postgres
    volumes:
      - myodoo10-data:/opt/odoo/data

  postgres:
    image: postgres:9.6.9
    restart: always
    volumes:
     - postgres-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=myodoo
     - POSTGRES_PASSWORD=myodoo

volumes:
  myodoo10-data:
  postgres-data:
```
